# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 80, 121);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_dashbord = QtWidgets.QPushButton(self.frame)
        self.btn_dashbord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dashbord.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    font-size: 16px;\n"
"    background-color: rgb(0, 80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}\n"
"\n"
"\n"
"")
        self.btn_dashbord.setObjectName("btn_dashbord")
        self.horizontalLayout.addWidget(self.btn_dashbord)
        self.btn_acao = QtWidgets.QPushButton(self.frame)
        self.btn_acao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_acao.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    font-size: 16px;\n"
"    background-color: rgb(0, 80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}")
        self.btn_acao.setObjectName("btn_acao")
        self.horizontalLayout.addWidget(self.btn_acao)
        self.btn_exportar = QtWidgets.QPushButton(self.frame)
        self.btn_exportar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exportar.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    font-size: 16px;\n"
"    background-color: rgb(0, 80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}")
        self.btn_exportar.setObjectName("btn_exportar")
        self.horizontalLayout.addWidget(self.btn_exportar)
        self.verticalLayout.addWidget(self.frame)
        self.Pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.Pages.setStyleSheet("\n"
"background-color: rgb(172, 172, 172);")
        self.Pages.setObjectName("Pages")
        self.pg_dashbord = QtWidgets.QWidget()
        self.pg_dashbord.setObjectName("pg_dashbord")
        self.txt_temperatura = QtWidgets.QTextEdit(self.pg_dashbord)
        self.txt_temperatura.setGeometry(QtCore.QRect(80, 40, 231, 171))
        self.txt_temperatura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_temperatura.setObjectName("txt_temperatura")
        self.txt_umidade = QtWidgets.QTextEdit(self.pg_dashbord)
        self.txt_umidade.setGeometry(QtCore.QRect(450, 40, 231, 171))
        self.txt_umidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_umidade.setObjectName("txt_umidade")
        self.txt_atualizacao = QtWidgets.QTextEdit(self.pg_dashbord)
        self.txt_atualizacao.setGeometry(QtCore.QRect(450, 290, 231, 181))
        self.txt_atualizacao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_atualizacao.setObjectName("txt_atualizacao")
        self.btn_atualizaInformacoes = QtWidgets.QPushButton(self.pg_dashbord)
        self.btn_atualizaInformacoes.setGeometry(QtCore.QRect(570, 480, 111, 31))
        self.btn_atualizaInformacoes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_atualizaInformacoes.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    border-radius: 3px;\n"
                                           "    font-size: 16px;\n"
                                           "    background-color: rgb(0, 80, 121);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}")
        self.btn_atualizaInformacoes.setObjectName("btn_atualizaInformacoes")
        self.txt_acao = QtWidgets.QTextEdit(self.pg_dashbord)
        self.txt_acao.setGeometry(QtCore.QRect(80, 290, 231, 181))
        self.txt_acao.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_acao.setObjectName("txt_acao")
        self.lb_temperatura = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_temperatura.setGeometry(QtCore.QRect(160, 20, 91, 18))
        self.lb_temperatura.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_temperatura.setObjectName("lb_temperatura")
        self.lb_umidade = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_umidade.setGeometry(QtCore.QRect(530, 20, 73, 18))
        self.lb_umidade.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_umidade.setObjectName("lb_umidade")
        self.lb_acao = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_acao.setGeometry(QtCore.QRect(170, 270, 41, 18))
        self.lb_acao.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_acao.setObjectName("lb_acao")
        self.lb_atualizacao0 = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_atualizacao0.setGeometry(QtCore.QRect(510, 230, 121, 20))
        self.lb_atualizacao0.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_atualizacao0.setObjectName("lb_atualizacao0")
        self.lb_atualizacao1 = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_atualizacao1.setGeometry(QtCore.QRect(560, 250, 21, 16))
        self.lb_atualizacao1.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_atualizacao1.setObjectName("lb_atualizacao1")
        self.lb_atualizacao2 = QtWidgets.QLabel(self.pg_dashbord)
        self.lb_atualizacao2.setGeometry(QtCore.QRect(510, 270, 121, 16))
        self.lb_atualizacao2.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_atualizacao2.setObjectName("lb_atualizacao2")
        self.Pages.addWidget(self.pg_dashbord)
        self.pg_acao = QtWidgets.QWidget()
        self.pg_acao.setObjectName("pg_acao")
        self.txt_acaoPreventiva = QtWidgets.QTextEdit(self.pg_acao)
        self.txt_acaoPreventiva.setGeometry(QtCore.QRect(120, 110, 561, 411))
        self.txt_acaoPreventiva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_acaoPreventiva.setObjectName("txt_acaoPreventiva")
        self.fr_topbar = QtWidgets.QFrame(self.pg_acao)
        self.fr_topbar.setGeometry(QtCore.QRect(120, 10, 561, 81))
        self.fr_topbar.setStyleSheet("")
        self.fr_topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_topbar.setObjectName("fr_topbar")
        self.btn_iniciarAcao = QtWidgets.QPushButton(self.fr_topbar)
        self.btn_iniciarAcao.setGeometry(QtCore.QRect(430, 23, 111, 31))
        self.btn_iniciarAcao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_iniciarAcao.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    font-size: 16px;\n"
"    background-color: rgb(0, 80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}")
        self.btn_iniciarAcao.setObjectName("btn_iniciarAcao")
        self.lb_agrotoxicoAcao = QtWidgets.QLabel(self.fr_topbar)
        self.lb_agrotoxicoAcao.setGeometry(QtCore.QRect(20, 50, 73, 18))
        self.lb_agrotoxicoAcao.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_agrotoxicoAcao.setObjectName("lb_agrotoxicoAcao")
        self.cb_agrotoxico = QtWidgets.QComboBox(self.fr_topbar)
        self.cb_agrotoxico.setGeometry(QtCore.QRect(100, 50, 141, 21))
        self.cb_agrotoxico.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_agrotoxico.setObjectName("cb_agrotoxico")
        self.lb_doencas = QtWidgets.QLabel(self.fr_topbar)
        self.lb_doencas.setGeometry(QtCore.QRect(32, 11, 61, 18))
        self.lb_doencas.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.lb_doencas.setObjectName("lb_doencas")
        self.cb_doencas = QtWidgets.QComboBox(self.fr_topbar)
        self.cb_doencas.setGeometry(QtCore.QRect(100, 10, 141, 21))
        self.cb_doencas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_doencas.setObjectName("cb_doencas")
        self.rb_normal = QtWidgets.QRadioButton(self.fr_topbar)
        self.rb_normal.setGeometry(QtCore.QRect(300, 10, 82, 17))
        self.rb_normal.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 10.5pt \"MS Shell Dlg 2\";\n"
"")
        self.rb_normal.setObjectName("rb_normal")
        self.rb_chuvoso = QtWidgets.QRadioButton(self.fr_topbar)
        self.rb_chuvoso.setGeometry(QtCore.QRect(300, 30, 82, 17))
        self.rb_chuvoso.setStyleSheet("font: 10.5pt \"MS Shell Dlg 2\";\n"
"")
        self.rb_chuvoso.setObjectName("rb_chuvoso")
        self.rb_seco = QtWidgets.QRadioButton(self.fr_topbar)
        self.rb_seco.setGeometry(QtCore.QRect(300, 50, 82, 17))
        self.rb_seco.setStyleSheet("font: 10.5pt \"MS Shell Dlg 2\";")
        self.rb_seco.setObjectName("rb_seco")
        self.Pages.addWidget(self.pg_acao)
        self.pg_exportar = QtWidgets.QWidget()
        self.pg_exportar.setObjectName("pg_exportar")
        self.frame_2 = QtWidgets.QFrame(self.pg_exportar)
        self.frame_2.setGeometry(QtCore.QRect(180, 120, 421, 291))
        self.frame_2.setStyleSheet("border:2.5px solid rgb(0, 80, 121);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setGeometry(QtCore.QRect(61, 140, 207, 31))
        self.radioButton_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border:2.5px solid rgb(0, 80, 121, 0,0);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_5.setGeometry(QtCore.QRect(61, 97, 197, 31))
        self.radioButton_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border:2.5px solid rgb(0, 80, 121, 0,0);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_6.setGeometry(QtCore.QRect(61, 183, 228, 31))
        self.radioButton_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border:2.5px solid rgb(0, 80, 121, 0,0);")
        self.radioButton_6.setObjectName("radioButton_6")
        self.btn_relatorio_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn_relatorio_2.setGeometry(QtCore.QRect(23, 250, 376, 25))
        self.btn_relatorio_2.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_relatorio_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_relatorio_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"    border:2px solid rgb(0, 80, 121);\n"
"    font-size: 16px;\n"
"    background-color: rgb(0, 80, 121);\n"
"}\n"
"\n"
"QPushButton:hover{background-color: #acacac; color:black; border:2px solid  rgb(0, 80, 121);}")
        self.btn_relatorio_2.setObjectName("btn_relatorio_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(23, 10, 376, 71))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"border-radius:3px;\n"
"border:2.5px solid rgb(0, 80, 121);")
        self.label.setObjectName("label")
        self.Pages.addWidget(self.pg_exportar)
        self.verticalLayout.addWidget(self.Pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dashbord.setText(_translate("MainWindow", "Dashbord"))
        self.btn_acao.setText(_translate("MainWindow", "Ação preventiva"))
        self.btn_exportar.setText(_translate("MainWindow", "Exportar"))
        self.btn_atualizaInformacoes.setText(_translate("MainWindow","Atualizar"))
        self.txt_temperatura.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">22°</span></p></body></html>"))
        self.txt_umidade.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">50%</span></p></body></html>"))
        self.txt_atualizacao.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Temperatura máxima:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Umidade máxima:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Data:</p></body></html>"))
        self.txt_acao.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Agrotóxico:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Inicio do Tratamento:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Próxima aplicação:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Ultima aplicação:</span></p></body></html>"))
        self.lb_temperatura.setText(_translate("MainWindow", "Temperatura"))
        self.lb_umidade.setText(_translate("MainWindow", "Umidade"))
        self.lb_acao.setText(_translate("MainWindow", "Ação"))
        self.lb_atualizacao0.setText(_translate("MainWindow", "Última atualização"))
        self.lb_atualizacao1.setText(_translate("MainWindow", "de"))
        self.lb_atualizacao2.setText(_translate("MainWindow", "Tempo e umidade"))
        self.btn_iniciarAcao.setText(_translate("MainWindow", "Iniciar"))
        self.lb_agrotoxicoAcao.setText(_translate("MainWindow", "Agrotóxico:"))
        self.lb_doencas.setText(_translate("MainWindow", "Doenças:"))
        self.rb_normal.setText(_translate("MainWindow", "Normal"))
        self.rb_chuvoso.setText(_translate("MainWindow", "Chuvoso"))
        self.rb_seco.setText(_translate("MainWindow", "Seco"))
        self.radioButton_4.setText(_translate("MainWindow", "Exportar agrotóxico"))
        self.radioButton_5.setText(_translate("MainWindow", "Exportar aplicação"))
        self.radioButton_6.setText(_translate("MainWindow", "Exportar últimas altas"))
        self.btn_relatorio_2.setText(_translate("MainWindow", "Exportar"))
        self.label.setText(_translate("MainWindow", "Selecione um para que seja exportado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
